## Introdução ao numpy

In [9]:
import numpy as np

In [10]:
heights = [189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175, 178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180 , 170, 178, 182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188, 182, 185, 191]
cnt = 0
for height in heights:
    if height> 188:
        cnt+=1
print(cnt)

5


In [11]:
heights_arr = np.array(heights)
print((heights_arr>188).sum())

5


In [14]:
heights_arr.size

45

In [15]:
heights_arr.shape

(45,)

In [37]:
ages = [57, 61, 57, 57, 58, 57, 61, 54, 68, 51, 49, 64, 50, 48, 65, 52, 56, 46, 54, 49, 51, 47, 55, 55, 54, 42, 51, 56, 55, 51, 54, 51, 60, 62, 43, 55, 56, 61, 52, 69, 64, 46, 54, 47, 70]
age_arr = np.array(ages)
heights_and_ages = heights + ages
# convert a list to a numpy array
heights_and_ages_arr = np.array(heights_and_ages)
heights_and_ages_arr.shape

(90,)

In [32]:
heights_and_ages_arr.reshape((2,45))

array([[189, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
        178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180, 170, 178,
        182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177,
        185, 188, 188, 182, 185, 191],
       [ 57,  61,  57,  57,  58,  57,  61,  54,  68,  51,  49,  64,  50,
         48,  65,  52,  56,  46,  54,  49,  51,  47,  55,  55,  54,  42,
         51,  56,  55,  51,  54,  51,  60,  62,  43,  55,  56,  61,  52,
         69,  64,  46,  54,  47,  70]])

In [25]:
heights_arr.dtype

dtype('int32')

In [27]:
heights_float = [189.0, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175, 178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180 , 170, 178, 182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177, 185, 188, 188, 182, 185, 191]
heights_float_arr = np.array(heights_float)
heights_float_arr
heights_float_arr.dtype

dtype('float64')

In [45]:
heights_arr = np.array(heights)
heights_arr = heights_arr.reshape ((45,1))
age_arr = age_arr.reshape ((45,1))
height_age_arr = np.hstack((heights_arr, age_arr))
height_age_arr.shape
height_age_arr[:3,]

array([[189,  57],
       [170,  61],
       [189,  57]])

In [47]:
heights_arr = heights_arr.reshape((1,45))
age_arr = age_arr.reshape((1,45))
height_age_arr = np.vstack((heights_arr, age_arr))
height_age_arr.shape 
height_age_arr[:,:3]

array([[189, 170, 189],
       [ 57,  61,  57]])

In [50]:
height_age_arr = np.concatenate((heights_arr, age_arr), axis=1)
height_age_arr.shape

(1, 90)

In [54]:
height_age_arr = np.concatenate((heights_arr, age_arr), axis = 0)
height_age_arr.shape

(2, 45)

In [55]:
height_age_arr[:,0]*0.0328084

array([6.2007876, 1.8700788])

In [58]:
height_age_arr.sum(axis=0)

array([246, 231, 246, 220, 241, 228, 246, 222, 241, 234, 222, 237, 225,
       226, 248, 245, 234, 219, 228, 232, 234, 227, 223, 235, 224, 220,
       233, 236, 238, 229, 236, 239, 235, 241, 226, 248, 238, 244, 229,
       254, 252, 234, 236, 232, 261])

In [59]:
height_age_arr[:,1]<55

array([False, False])

In [60]:
height_age_arr[:,1]==51

array([False, False])

In [64]:
(height_age_arr[:,1]==51).sum()

0

In [65]:
mask = height_age_arr[:,0]>=182
mask.sum()

1

In [67]:
tall_presidents = height_age_arr[mask,]
tall_presidents.shape

(1, 45)

In [68]:
mask = (height_age_arr[:,0]>=182)&(height_age_arr[:,1]<=50)
height_age_arr[mask,]

array([], shape=(0, 45), dtype=int32)